# Generated by Django 3.2.14 on 2023-03-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('img_path', models.CharField(max_length=255, null=True)),
                ('action_url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'home_contents',
            },
        ),
        migrations.CreateModel(
            name='NetFigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_figpath', models.CharField(max_length=255, null=True)),
                ('dr_figpath', models.CharField(max_length=255, null=True)),
                ('dr_rep_figpath', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'net_figs',
            },
        ),
        migrations.CreateModel(
            name='Nets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_z', models.IntegerField()),
                ('n_layer', models.IntegerField()),
                ('n_count', models.IntegerField()),
                ('rep', models.FloatField(null=True)),
                ('dr', models.FloatField(null=True)),
                ('dr_0', models.FloatField(null=True)),
                ('dr_1', models.FloatField(null=True)),
                ('dr_2', models.FloatField(null=True)),
                ('dr_3', models.FloatField(null=True)),
                ('dr_4', models.FloatField(null=True)),
                ('dr_5', models.FloatField(null=True)),
                ('dr_6', models.FloatField(null=True)),
                ('dr_7', models.FloatField(null=True)),
                ('dr_8', models.FloatField(null=True)),
                ('dr_9', models.FloatField(null=True)),
                ('id_net', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'nets',
            },
        ),
        migrations.CreateModel(
            name='GenImgs',
            fields=[
                ('genimgs_dir', models.CharField(max_length=255, null=True)),
                ('net', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vaes.nets')),
            ],
            options={
                'db_table': 'gen_imgs',
            },
        ),
    ]
