# Generated by Django 3.2.14 on 2023-02-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nets',
            name='price',
        ),
    ]
