# Generated by Django 3.2.14 on 2023-02-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaes', '0002_remove_nets_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nets',
            name='name',
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_0',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='dr_9',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nets',
            name='dr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nets',
            name='rep',
            field=models.FloatField(null=True),
        ),
    ]
