# Generated by Django 3.2.14 on 2023-02-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaes', '0003_auto_20230207_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nets',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='nets',
            name='update_at',
        ),
        migrations.CreateModel(
            name='NetFigures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_fig', models.FileField(null=True, upload_to='net_figures/')),
                ('dr_rep_fig', models.FileField(null=True, upload_to='net_figures/')),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaes.nets')),
            ],
            options={
                'db_table': 'net_figures',
            },
        ),
        migrations.CreateModel(
            name='GeneratedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_all', models.FileField(null=True, upload_to='gen_imgs/')),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaes.nets')),
            ],
            options={
                'db_table': 'generated_images',
            },
        ),
    ]
