# Generated by Django 3.2.14 on 2023-02-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaes', '0005_auto_20230214_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genimgs',
            name='id',
        ),
        migrations.AlterField(
            model_name='genimgs',
            name='net',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vaes.nets'),
        ),
    ]
