# Generated by Django 3.2.14 on 2023-02-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaes', '0006_auto_20230219_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genimgs',
            old_name='label_0_imgpath',
            new_name='genimgs_dir',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_1_imgpath',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_2_imgpath',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_3_imgpath',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_4_imgpath',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_5_imgpath',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_6_imgpath',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_7_imgpath',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_8_imgpath',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_9_imgpath',
        ),
        migrations.RemoveField(
            model_name='genimgs',
            name='label_all_imgpath',
        ),
    ]
