# Generated by Django 3.2.14 on 2023-02-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaes', '0007_auto_20230224_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='nets',
            name='id_net',
            field=models.IntegerField(null=True),
        ),
    ]
