# Generated by Django 3.2.14 on 2023-03-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaes', '0008_nets_id_net'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('img_path', models.CharField(max_length=255, null=True)),
                ('link_path', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'home_contents',
            },
        ),
    ]
