# Generated by Django 3.2.14 on 2023-03-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaes', '0009_homecontents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecontents',
            old_name='link_path',
            new_name='action',
        ),
    ]
