# Generated by Django 3.2.14 on 2023-03-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaes', '0010_rename_link_path_homecontents_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecontents',
            old_name='action',
            new_name='action_url',
        ),
    ]
